description:
  map_name: "test_field_1"
  date: "24.12.23"
  text: "high maze"
  complete: 100

border:
  type: 'border'
  coordinates: [ [ 10, 10 ], [ 1270, 10 ], [ 1270, 710 ], [ 10, 710 ] ]

rectangles:
  square_1:
    coordinates: [ [ 215.0, 10.0 ], [ 225.0, 10.0 ], [ 215.0, 476.0 ], [ 225.0, 476.0 ] ]

  square_2:
    coordinates: [ [ 220.0, 471.0 ], [ 1060.0, 471.0 ], [ 220.0, 481.0 ], [ 1060.0, 481.0 ] ]

  square_3:
    coordinates: [ [ 425.0, 10.0 ], [ 435.0, 10.0 ], [ 425.0, 243.0 ], [ 435.0, 243.0 ] ]

  square_4:
    coordinates: [ [ 635.0, 10.0 ], [ 645.0, 10.0 ], [ 635.0, 243.0 ], [ 645.0, 243.0 ] ]

  square_5:
    coordinates: [ [ 845.0, 243.0 ], [ 855.0, 243.0 ], [ 845.0, 476.0 ], [ 855.0, 476.0 ] ]

  square_6:
    coordinates: [ [ 1060.0, 238.0 ], [ 1270.0, 238.0 ], [ 1060.0, 248.0 ], [ 1270.0, 248.0 ] ]

